### PR TITLE
Add GitHub CI

### PR DESCRIPTION
**Pull request by pjoe**
This adds initial CI using github actions.

Currently only web-min-nocompute and node-devel is build, but easy enough to add the other configs.

Also added a very basic test using jest that is run on each build. Will add better tests later :)

### CODE REVIEW

**Comment by pjoe** [comment]
Hmm looks like the jest test is failing on GitHub even though it works locally, maybe something with specific node.js version.

Will take a look at converting to TypeScript tomorrow

**Comment by kainino0x** [comment]
Since you're setting up tests, it would be useful to replicate the 3 test shaders from https://github.com/kainino0x/glslang.js/blob/master/tests/helper.mjs

> Will take a look at converting to TypeScript tomorrow

I don't think there's any need to use typescript for a few small tests, probably easier if we don't add more complexity to the build.

**Comment by pjoe** [comment]
I saw the tests in helper.mjs, but ended up starting with something even simpler - just to get it working. My thinking was that after that I would try adding some of the tests from glslang itself: https://github.com/kainino0x/glslang/tree/851f3daad0efb7e69a6bec4fd07fe60067104a4a/Test. Maybe even validate the output too :)

About TypeScript: as it's currently failing with some issue between jest and babel, I was merely thinking that this could be avoided by running the tests through ts (guess I'm also so used to it, that it's sort of second nature to me by now). Will try some more if I can get it working with just plain old js.

**Comment by pjoe** [comment]
After spending a bit more time investigating, seems like jest and mjs really are not good friends (yet): https://github.com/facebook/jest/issues/9430

At least I got it failing the same way locally, not sure how I had it working before :s

Will give it a try with typescript, as this is something I know 'should work' tm :D

**Comment by pjoe** [comment]
Hmm after even more investigation:

Something is wonky with the gslang build itself.

When only building `node-devel` it generates glslang.js with ESM and Promise. If building `web-min-nocompute` AND `node-devel` it generates glslang.js with normal node.js exports :S

**Comment by pjoe** [comment]
Got it working now: https://github.com/pjoe/glslang.js/runs/528548315?check_suite_focus=true

For some obscure reason have to run the node-devel build twice to get it to create the correct .js file without ESM promise loader using `import.meta`

Also added the tests from helper.mjs properly setup with jest

**Comment by pjoe** [comment]
Let's merge first :)

Would still like to figure out the build issue, but that can be done afterwards. I also suspect the issue is in glslang itself and not in this repo, but not sure.

**Pull request merged**
